### ISSUE TITLE
Installing browser via cmd line fails 

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sheet-icons#496]
### What version of Butler Sheet Icons are you using?

3.2.3

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler Sheet Icons.

21.6.1

### What command did you use to start Butler Sheet Icons?

node ./butler-sheet-icons.js browser install

### What operating system are you using?

macOS

### What CPU architecture are you using?

x86

### What Qlik Sense versions are you using?

2023-Nov

### Describe the Bug

Creating sheet thumbnails for both cloud and QSEoW works, including installation of browser if needed.

The `.\butler-sheet-icons.exe browser install` does however fail, both when executed like that and when passing in a specific browser version number.

```
➜  src git:(puppeteer20) ✗ /Users/goran/.nvm/versions/node/v21.6.1/bin/node ./butler-sheet-icons.js browser install
2024-02-15T12:23:36.480Z info: Resolved browser build id: "121.0.6167.184" for browser "chrome" version "stable"
2024-02-15T12:23:36.481Z info: Installing browser...
2024-02-15T12:23:36.837Z error: Browser version "stable" not found
2024-02-15T12:23:36.837Z error: BROWSER MAIN 9: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-x64/chrome-mac-x64.zip
2024-02-15T12:23:36.837Z error: BROWSER MAIN 9 (message): Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-x64/chrome-mac-x64.zip
2024-02-15T12:23:36.838Z error: BROWSER MAIN 9 (stack): Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-x64/chrome-mac-x64.zip
    at /Users/goran/code/butler-sheet-icons/src/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:92:31
    at ClientRequest.requestCallback (/Users/goran/code/butler-sheet-icons/src/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:69:13)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:690:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:532:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by mountaindude** [comment]
Turns out that some of the Chrome versions listed as existing cannot be downloaded by Puppeteer.

BSI has been changed to show which Chrome versions are available:

```
➜  node ./src/butler-sheet-icons.js browser list-available --loglevel verbose
2024-02-15T19:33:46.928Z verbose: Starting check for available browser versions
2024-02-15T19:33:46.931Z verbose: Running as standalone app: false
2024-02-15T19:33:47.249Z info: Chrome versions from "stable" channel:
2024-02-15T19:33:47.847Z info:     122.0.6261.49, "chrome/platforms/mac/channels/stable/versions/122.0.6261.49" (not available)
2024-02-15T19:33:48.378Z info:     121.0.6167.184, "chrome/platforms/mac/channels/stable/versions/121.0.6167.184" (not available)
2024-02-15T19:33:48.870Z info:     121.0.6167.160, "chrome/platforms/mac/channels/stable/versions/121.0.6167.160" (not available)
2024-02-15T19:33:49.262Z info:     121.0.6167.139, "chrome/platforms/mac/channels/stable/versions/121.0.6167.139" (not available)
2024-02-15T19:33:49.340Z info:     121.0.6167.85, "chrome/platforms/mac/channels/stable/versions/121.0.6167.85"
2024-02-15T19:33:49.419Z info:     121.0.6167.75, "chrome/platforms/mac/channels/stable/versions/121.0.6167.75"
2024-02-15T19:33:49.817Z info:     120.0.6099.234, "chrome/platforms/mac/channels/stable/versions/120.0.6099.234" (not available)
2024-02-15T19:33:50.329Z info:     120.0.6099.216, "chrome/platforms/mac/channels/stable/versions/120.0.6099.216" (not available)
2024-02-15T19:33:50.757Z info:     120.0.6099.199, "chrome/platforms/mac/channels/stable/versions/120.0.6099.199" (not available)
```

**Comment by mountaindude** [comment]
Update:

`list-available` command should work like this:

- With `info` level logging: Only list those browser versions that are actually available for Puppeteer (and thus Butler Sheet Icons) to download and use.
- With `verbose` level logging: List also those browser versions that exist, but are *not* available to Puppeteer.

Something like this:

```bash
node ./butler-sheet-icons.js browser list-available --loglevel verbose --channel stable
2024-02-16T07:38:37.083Z info: App version: 3.2.3
2024-02-16T07:38:37.086Z verbose: Starting check for available browser versions
2024-02-16T07:38:37.086Z verbose: Running as standalone app: false
2024-02-16T07:38:37.371Z info: Chrome versions from "stable" channel:
2024-02-16T07:38:37.372Z verbose: Note that not all versions may be available for use with Butler Sheet Icons.
2024-02-16T07:38:37.936Z verbose:     122.0.6261.49, "chrome/platforms/mac/channels/stable/versions/122.0.6261.49" (not available)
2024-02-16T07:38:38.446Z verbose:     121.0.6167.184, "chrome/platforms/mac/channels/stable/versions/121.0.6167.184" (not available)
2024-02-16T07:38:38.983Z verbose:     121.0.6167.160, "chrome/platforms/mac/channels/stable/versions/121.0.6167.160" (not available)
2024-02-16T07:38:39.489Z verbose:     121.0.6167.139, "chrome/platforms/mac/channels/stable/versions/121.0.6167.139" (not available)
2024-02-16T07:38:39.535Z info:     121.0.6167.85, "chrome/platforms/mac/channels/stable/versions/121.0.6167.85"
2024-02-16T07:38:39.568Z info:     121.0.6167.75, "chrome/platforms/mac/channels/stable/versions/121.0.6167.75"
2024-02-16T07:38:40.075Z verbose:     120.0.6099.234, "chrome/platforms/mac/channels/stable/versions/120.0.6099.234" (not available)
2024-02-16T07:38:40.577Z verbose:     120.0.6099.216, "chrome/platforms/mac/channels/stable/versions/120.0.6099.216" (not available)
2024-02-16T07:38:41.155Z verbose:     120.0.6099.199, "chrome/platforms/mac/channels/stable/versions/120.0.6099.199" (not available)
```
