### ISSUE TITLE
Error: Could not load the "sharp" module using the win32-x64 runtime

### ISSUE THREAD

**Issue by Chase-Stevison** [ptarmiganlabs/butler-sheet-icons#622]
### What version of Butler Sheet Icons are you using?

3.7.1

### What command did you use to start Butler Sheet Icons?

butler-sheet-icons.exe

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

Feb 2023

### Describe the Bug

Error thrown without any parameters:
```
PS C:\Butler Sheet Icons> .\butler-sheet-icons.exe
(node:18720) Warning: Currently the require() provided to the main script embedded into single-executable applications only supports loading built-in modules.
To load a module from disk after the single executable application is launched, use require("module").createRequire().
Support for bundled module loading or virtual file systems are under discussions in https://github.com/nodejs/single-executable
(Use `butler-sheet-icons --trace-warnings ...` to show where the warning was created)
build.cjs:118475
      throw new Error(help.join("\n"));
      ^

Error: Could not load the "sharp" module using the win32-x64 runtime
ERR_UNKNOWN_BUILTIN_MODULE: No such built-in module: ../src/build/Release/sharp-win32-x64.node
ERR_UNKNOWN_BUILTIN_MODULE: No such built-in module: ../src/build/Release/sharp-wasm32.node
ERR_UNKNOWN_BUILTIN_MODULE: No such built-in module: @img/sharp-win32-x64/sharp.node
ERR_UNKNOWN_BUILTIN_MODULE: No such built-in module: @img/sharp-wasm32/sharp.node
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at node_modules/sharp/lib/sharp.js (build.cjs:118475:13)
    at __require (build.cjs:9:50)
    at node_modules/sharp/lib/constructor.js (build.cjs:118487:5)
    at __require (build.cjs:9:50)
    at node_modules/sharp/lib/index.js (build.cjs:121487:17)
    at __require (build.cjs:9:50)
    at lib/qseow/qseow-create-thumbnails.js (build.cjs:136162:17)
    at __require (build.cjs:9:50)
    at build.cjs:142762:33
    at embedderRunCjs (node:internal/main/embedding:87:10)

Node.js v23.1.0
```

### Expected Behavior

Display help information

### To Reproduce

Run butler-sheet-icons.exe via PowerShell 7.x or Windows PowerShell 5.1

**Comment by jsebright** [comment]
Same issue for me, running QSEOW Nov 2024 on Win Server 2022 21H2.

**Comment by mountaindude** [comment]
Sorry for not resolving this sooner, but [3.8.0 is out](https://github.com/ptarmiganlabs/butler-sheet-icons/releases) and should fix the (very nasty) bug you encountered.
Long story short, this was an issue on Windows, while macOS worked fine. 

Butler Sheet Icons was refactored in the last version and is now easier to maintain and develop compared to before - that's a good thing :)

**Comment by jsebright** [comment]
Many thanks, look forward to trying this again.
